# Generated by Django 3.2.6 on 2021-09-27 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('exam_courses', '0001_initial'),
        ('checkout', '0002_auto_20210925_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='exam_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_courses.examcourse'),
        ),
    ]
