# Generated by Django 3.2.6 on 2021-10-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('reviews', '0004_alter_review_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
